import type { Metadata } from "next";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "next-frontend-starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="bottom-right" toastOptions={{ duration: 5000 }} />
        <nav className="flex w-full space-x-6 bg-gray-300 p-4">
          <h1 className="font-bold">ÁLK Utazási Iroda</h1>
          <Link className="cursor-pointer transition-transform hover:scale-110" href="/journeys">
            Kínálatunk
          </Link>
          <Link
            className="cursor-pointer transition-transform hover:scale-110"
            href="/registration"
          >
            Regisztráció
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
